version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "server"

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"
        reservations:
          cpus: "0.25"
          memory: "250M"
